'use strict';

/*
// Lecture 64
// Project #1
// Easy way of selecting element in JS
console.log(document.querySelector('.message').textContent);
*/
////////////////////////////

/*
// Lecture 65
// What is the DOM and DOM Manipulation
// DOM Manipulation is a technical term which means
// JS interacting with webpage.

// DOM
// Is a structure representation og the HTML documents

// DOM is a connection point between HTML document and the JS code. 

// DOM Tree
// Is a Tree structure generated by the browser on HTML loads.
*/
/////////////////////////////////////

// Lecture 66
// Selecting and Manipulating Elements
document.querySelector('.message').textContent = '🎉 Correct Number!';
console.log(document.querySelector('.message').textContent);

document.querySelector('.number').textContent = 13;
document.querySelector('.score').textContent = 13;

// Use the .value property to get the actual
// values of input field
// Use the .value property to manipulate the input
// element its values
document.querySelector('.guess').value = 3;
console.log(document.querySelector('.guess').value);
